name = "sveltekit-firebaseauth-ssr-stripe-demo"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-09-06"

[[kv_namespaces]]
binding = "KV"
id = "cc61b1444bc2402dada2541b9ae18c49"

[vars]
PUBLIC_FIREBASE_PROJECT_ID = "sveltekit-firebaseauth-ssr"
PUBLIC_FIREBASE_API_KEY = "AIzaSyAszoTYS-QorJLFhXB6_d5iE83hScl2LjI"
PUBLIC_FIREBASE_AUTH_EMULATOR_HOST = ""