name = "sveltekit-firebaseauth-ssr-stripe-demo"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-09-06"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV"
id = "cc61b1444bc2402dada2541b9ae18c49"
